#!/usr/bin/env sh
set -eu

APP_URL="${APP_URL:-https://app.autopilot-one.com}"
API_URL="${API_URL:-https://api.autopilot-one.com/api}"
TMP_DIR="${TMP_DIR:-/tmp/autopilot-functional-pilot-qa}"
RUN_ID="${RUN_ID:-$(date +%Y%m%d%H%M%S)}"
RUN_DEMO_REQUEST="${RUN_DEMO_REQUEST:-1}"
RUN_RECEPTION_AI_MESSAGE="${RUN_RECEPTION_AI_MESSAGE:-1}"

PILOT_EMAIL="${PILOT_EMAIL:-pilot-qa-$RUN_ID@example.com}"
PILOT_PASSWORD="${PILOT_PASSWORD:-AutopilotQA-$RUN_ID!}"
PILOT_ORG_NAME="${PILOT_ORG_NAME:-Autopilot QA $RUN_ID}"
PILOT_ORG_SLUG="${PILOT_ORG_SLUG:-autopilot-qa-$RUN_ID}"

mkdir -p "$TMP_DIR"

fail() {
  echo "FAIL: $*" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || fail "missing required command: $1"
}

expect_code() {
  code="$1"
  allowed="$2"
  for expected in $allowed; do
    [ "$code" = "$expected" ] && return 0
  done
  return 1
}

json_get_file() {
  file="$1"
  path="$2"
  python3 - "$file" "$path" <<'PY'
import json
import sys

file_path = sys.argv[1]
path = sys.argv[2].split('.')
with open(file_path, 'r', encoding='utf-8') as handle:
    data = json.load(handle)

value = data
for item in path:
    if isinstance(value, dict):
        value = value.get(item)
    else:
        value = None
    if value is None:
        break

if value is None:
    sys.exit(1)
if isinstance(value, (dict, list)):
    print(json.dumps(value, ensure_ascii=False))
else:
    print(value)
PY
}

json_len_file() {
  file="$1"
  python3 - "$file" <<'PY'
import json
import sys
with open(sys.argv[1], 'r', encoding='utf-8') as handle:
    data = json.load(handle)
if isinstance(data, list):
    print(len(data))
elif isinstance(data, dict):
    print(len(data.keys()))
else:
    print(0)
PY
}

api_json() {
  method="$1"
  path="$2"
  payload_file="$3"
  out_file="$4"
  allowed_codes="$5"
  auth_mode="${6:-public}"

  if [ "$auth_mode" = "auth" ]; then
    if [ -n "$payload_file" ]; then
      code="$(curl -k -sS -L -X "$method" \
        -H 'Content-Type: application/json' \
        -H "Authorization: Bearer $ACCESS_TOKEN" \
        --data-binary "@$payload_file" \
        -o "$out_file" -w "%{http_code}" \
        "$API_URL$path" || true)"
    else
      code="$(curl -k -sS -L -X "$method" \
        -H 'Content-Type: application/json' \
        -H "Authorization: Bearer $ACCESS_TOKEN" \
        -o "$out_file" -w "%{http_code}" \
        "$API_URL$path" || true)"
    fi
  else
    if [ -n "$payload_file" ]; then
      code="$(curl -k -sS -L -X "$method" \
        -H 'Content-Type: application/json' \
        --data-binary "@$payload_file" \
        -o "$out_file" -w "%{http_code}" \
        "$API_URL$path" || true)"
    else
      code="$(curl -k -sS -L -X "$method" \
        -H 'Content-Type: application/json' \
        -o "$out_file" -w "%{http_code}" \
        "$API_URL$path" || true)"
    fi
  fi

  echo "$method $path code=$code"
  if ! expect_code "$code" "$allowed_codes"; then
    echo "--- response body ---" >&2
    cat "$out_file" >&2 || true
    echo >&2
    fail "$method $path returned $code, expected one of: $allowed_codes"
  fi
}

web_route() {
  path="$1"
  out_file="$TMP_DIR/web_$(printf '%s' "$path" | sed 's#/#_#g; s#^_$#home#').html"
  code="$(curl -k -sS -L -H 'Cache-Control: no-cache' -o "$out_file" -w "%{http_code}" "$APP_URL$path?qa=$RUN_ID" || true)"
  echo "$path code=$code"
  [ "$code" = "200" ] || fail "$APP_URL$path returned $code"
}

require_command curl
require_command python3

echo "=== Autopilot One Functional Pilot QA ==="
date -u +"Timestamp UTC: %Y-%m-%dT%H:%M:%SZ"
echo "App URL: $APP_URL"
echo "API URL: $API_URL"
echo "Run ID: $RUN_ID"
echo "Pilot email: $PILOT_EMAIL"
echo "Pilot organization slug: $PILOT_ORG_SLUG"

echo
 echo "=== PUBLIC WEB ROUTES ==="
for path in / /demo /pricing /login /register /dashboard /widget-demo; do
  web_route "$path"
done

echo
 echo "=== API HEALTH ==="
api_json GET /health "" "$TMP_DIR/health.json" "200"
grep -Eq '"status"[[:space:]]*:[[:space:]]*"ok"' "$TMP_DIR/health.json" || fail "API health did not return status ok"

if [ "$RUN_DEMO_REQUEST" = "1" ]; then
  echo
  echo "=== PUBLIC DEMO REQUEST ==="
  cat > "$TMP_DIR/demo-request.json" <<JSON
{
  "name": "Autopilot QA $RUN_ID",
  "email": "demo-$RUN_ID@example.com",
  "company": "Autopilot QA",
  "phone": "+40000000000",
  "website": "$APP_URL",
  "message": "Functional pilot QA request generated by Build 078A. Please ignore this test lead.",
  "source": "build-078a-functional-pilot-qa"
}
JSON
  api_json POST /demo-requests "$TMP_DIR/demo-request.json" "$TMP_DIR/demo-response.json" "200 201"
else
  echo
  echo "=== PUBLIC DEMO REQUEST SKIPPED ==="
fi

echo
 echo "=== REGISTER PILOT USER ==="
cat > "$TMP_DIR/register.json" <<JSON
{
  "email": "$PILOT_EMAIL",
  "password": "$PILOT_PASSWORD",
  "firstName": "Pilot",
  "lastName": "QA",
  "organizationName": "$PILOT_ORG_NAME",
  "organizationSlug": "$PILOT_ORG_SLUG",
  "country": "RO",
  "language": "ro",
  "timezone": "Europe/Bucharest"
}
JSON
api_json POST /auth/register "$TMP_DIR/register.json" "$TMP_DIR/register-response.json" "200 201"
ACCESS_TOKEN="$(json_get_file "$TMP_DIR/register-response.json" accessToken)" || fail "could not read accessToken from register response"
ORG_ID="$(json_get_file "$TMP_DIR/register-response.json" organization.id)" || fail "could not read organization.id from register response"
echo "Registered organization id: $ORG_ID"

echo
 echo "=== LOGIN PILOT USER ==="
cat > "$TMP_DIR/login.json" <<JSON
{
  "email": "$PILOT_EMAIL",
  "password": "$PILOT_PASSWORD"
}
JSON
api_json POST /auth/login "$TMP_DIR/login.json" "$TMP_DIR/login-response.json" "200 201"
LOGIN_ACCESS_TOKEN="$(json_get_file "$TMP_DIR/login-response.json" accessToken)" || fail "could not read accessToken from login response"
[ -n "$LOGIN_ACCESS_TOKEN" ] || fail "empty access token from login"
ACCESS_TOKEN="$LOGIN_ACCESS_TOKEN"

echo
 echo "=== ORGANIZATION READS ==="
api_json GET /organizations "" "$TMP_DIR/organizations.json" "200" auth
org_count="$(json_len_file "$TMP_DIR/organizations.json")"
echo "organizations visible=$org_count"
[ "$org_count" -ge 1 ] || fail "registered user cannot see any organizations"
api_json GET "/organizations/$ORG_ID" "" "$TMP_DIR/organization.json" "200" auth
api_json GET "/organizations/$ORG_ID/widget-settings" "" "$TMP_DIR/widget-settings.json" "200" auth

echo
 echo "=== KNOWLEDGE BASE TEXT SOURCE ==="
cat > "$TMP_DIR/kb-text-source.json" <<JSON
{
  "organizationId": "$ORG_ID",
  "title": "Build 078A pilot QA services",
  "content": "Autopilot QA offers reception AI, website widget, CRM Lite, lead follow-up and guided onboarding. Pilot support is available in Romanian and English.",
  "fileName": "build-078a-pilot-qa.txt"
}
JSON
api_json POST /knowledge-base/text "$TMP_DIR/kb-text-source.json" "$TMP_DIR/kb-create-response.json" "200 201" auth
api_json GET "/knowledge-base/organization/$ORG_ID/sources" "" "$TMP_DIR/kb-sources.json" "200" auth

cat > "$TMP_DIR/kb-search.json" <<JSON
{
  "organizationId": "$ORG_ID",
  "query": "reception AI CRM Lite pilot support",
  "limit": 5
}
JSON
api_json POST /knowledge-base/search "$TMP_DIR/kb-search.json" "$TMP_DIR/kb-search-response.json" "200 201" auth

echo
 echo "=== RECEPTION AI INTERNAL MESSAGE ==="
if [ "$RUN_RECEPTION_AI_MESSAGE" = "1" ]; then
  cat > "$TMP_DIR/reception-message.json" <<JSON
{
  "organizationId": "$ORG_ID",
  "message": "Bună, vreau o ofertă pentru recepționer AI, widget pe website și CRM Lite. Mă puteți contacta mâine?",
  "customerName": "Client QA $RUN_ID",
  "customerEmail": "client-$RUN_ID@example.com",
  "channel": "build-078a-functional-pilot-qa"
}
JSON
  api_json POST /reception-ai/message "$TMP_DIR/reception-message.json" "$TMP_DIR/reception-response.json" "200 201" auth
  CONVERSATION_ID="$(json_get_file "$TMP_DIR/reception-response.json" conversationId)" || fail "could not read conversationId from reception response"
  echo "conversationId=$CONVERSATION_ID"
else
  echo "Reception AI message skipped. Set RUN_RECEPTION_AI_MESSAGE=1 to run it."
fi

echo
 echo "=== INBOX / LEADS / TASKS / DASHBOARD READS ==="
api_json GET "/reception-ai/organization/$ORG_ID/summary" "" "$TMP_DIR/reception-summary.json" "200" auth
api_json GET "/reception-ai/organization/$ORG_ID/conversations" "" "$TMP_DIR/reception-conversations.json" "200" auth
api_json GET "/reception-ai/organization/$ORG_ID/leads" "" "$TMP_DIR/reception-leads.json" "200" auth
api_json GET "/reception-ai/organization/$ORG_ID/tasks" "" "$TMP_DIR/reception-tasks.json" "200" auth
api_json GET "/inbox/organization/$ORG_ID/conversations" "" "$TMP_DIR/inbox-conversations.json" "200" auth
api_json GET "/dashboard/organization/$ORG_ID" "" "$TMP_DIR/dashboard.json" "200" auth

echo
 echo "=== BILLING READS ==="
api_json GET "/billing/organization/$ORG_ID" "" "$TMP_DIR/billing.json" "200" auth

echo
 echo "=== OUTPUT SUMMARY ==="
echo "Temporary QA files: $TMP_DIR"
echo "Pilot email: $PILOT_EMAIL"
echo "Pilot password was generated for this run only. Do not reuse it."
echo "Pilot organization id: $ORG_ID"
echo "Pilot organization slug: $PILOT_ORG_SLUG"

echo
 echo "=== FUNCTIONAL PILOT QA PASSED ==="
